In [1]:
#missing values
#this  is useful for theidentify the missing values find this values and fill this im that time it missng value oprtion perfrom the  main role.

In [3]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [4]:
dict={
    'A':[1,2,np.nan],
    'B':[1,np.nan,np.nan],
    'C':[1,2,3]
}

In [6]:
dict

{'A': [1, 2, nan], 'B': [1, nan, nan], 'C': [1, 2, 3]}

In [7]:
df=pd.DataFrame(dict)

In [8]:
df

A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [10]:
df.dropna()

A    B  C
0  1.0  1.0  1

In [11]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [12]:
df.fillna(value='FillValue')

A          B  C
0        1.0        1.0  1
1        2.0  FillValue  2
2  FillValue  FillValue  3

In [13]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [15]:
df['B'].fillna(value=df['B'].mean())

0    1.0
1    1.0
2    1.0
Name: B, dtype: float64

In [16]:
df

A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [19]:
df=np.arange(10)

In [20]:
df

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros(1)

array([0.])

In [23]:
df=np.zeros((5,5))

In [24]:
df

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
df=np.ones((5,6))

In [26]:
df

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
df=np.arange(23)

In [28]:
df

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [29]:
df.min()

0

In [30]:
df.shape

(23,)

In [31]:
df.max()

22

In [36]:
df=pd.DataFrame([1,2,3,4],('gana','pooja','kunal','shewta'))
lables=['a','b','c','d']