In [2]:
#NUMPY ARRAY

In [3]:
import numpy as np

In [4]:
my_list=['gana','atharv','guru']

In [5]:
np.array(my_list)

array(['gana', 'atharv', 'guru'], dtype='<U6')

In [6]:
my_dat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_dat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(1)

array([0.])

In [10]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [14]:
np.random.rand(5)

array([0.23133998, 0.90019466, 0.98240058, 0.1672206 , 0.3180908 ])

In [15]:
np.random.rand(5,5)

array([[0.37422183, 0.28345903, 0.621729  , 0.01376102, 0.48153194],
       [0.27347924, 0.95397428, 0.81156339, 0.79042575, 0.61760415],
       [0.44826528, 0.14382736, 0.31303879, 0.04875082, 0.35485549],
       [0.73251439, 0.04098447, 0.13647661, 0.94675998, 0.71509836],
       [0.5144473 , 0.38699122, 0.35956532, 0.07869124, 0.21582125]])

In [16]:
np.random.randn(5)

array([-1.53219606,  0.41772831, -1.93173584, -1.86848676, -0.51458291])

In [17]:
np.random.randint(0,100,10)

array([53, 29, 97, 79, 22, 99, 48, 59, 65, 42])

In [18]:
arr=np.random.rand(5)

In [19]:
arr


array([0.24423541, 0.76923475, 0.61471716, 0.84775224, 0.45749591])

In [20]:
arr=np.array(25)

In [21]:
arr

array(25)

In [28]:
ant=np.random.randint(1,100,50)

In [29]:
ant

array([47, 40, 96, 92, 52, 25, 31, 69, 68, 33, 97, 19, 15, 30, 63, 30, 89,
       53, 91, 77, 52, 62, 27, 97, 14, 71, 38, 37, 20, 79, 76, 91, 18, 90,
       95, 74,  5, 51, 79, 47, 75, 17, 33, 44, 95, 35, 43, 95, 33,  1])

In [30]:
ant.max()

97

In [31]:
ant.min()

1

In [32]:
ant.argmax()

10

In [33]:
ant.argmin()

49

In [35]:
ant.shape

(50,)

In [ ]:
ant.reshape(56
)